### ISSUE TITLE
How volumes works?

### ISSUE THREAD

**Issue by lagden** [osirisguitar/rethinkdb-cluster-docker#1]
Hi,

Do I have to set up one volume for all containers?

**Example:**

```yaml
  # ...
  rethinkdb1:
    build: ./rethinkdb
    environment:
      - "DBCLUSTERHOSTS=rethinkdb2;rethinkdb3"
      - "RETHINKARGS=--server-tag primary --server-name rethinkdb1 --bind all"
    hostname: rethinkdb1
    networks:
      - rethink-net
    ports:
      - "8081:8080"
    volumes:
      - db-data:/data

  rethinkdb2:
    # ...
    volumes:
      - db-data:/data

  # ...

volumes:
  db-data:
```

Regards!

**Comment by lagden** [comment]
I created one volume to each container...

```yml
volumes:
  db-data-rdb1:
  db-data-rdb2:
  db-data-rdb3:
```
